name: weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  dio: ^5.3.3
  path_provider: ^2.1.1
  bot_toast: ^4.1.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/font/Raleway/static/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway/static/Raleway-Black.ttf
        - asset: assets/font/Raleway/static/Raleway-BlackItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-Bold.ttf
        - asset: assets/font/Raleway/static/Raleway-BoldItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-ExtraBold.ttf
        - asset: assets/font/Raleway/static/Raleway-ExtraBoldItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-ExtraLight.ttf
        - asset: assets/font/Raleway/static/Raleway-ExtraLightItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-Italic.ttf
        - asset: assets/font/Raleway/static/Raleway-Light.ttf
        - asset: assets/font/Raleway/static/Raleway-LightItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-Medium.ttf
        - asset: assets/font/Raleway/static/Raleway-MediumItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-Regular.ttf
        - asset: assets/font/Raleway/static/Raleway-SemiBold.ttf
        - asset: assets/font/Raleway/static/Raleway-SemiBoldItalic.ttf
        - asset: assets/font/Raleway/static/Raleway-Thin.ttf
        - asset: assets/font/Raleway/static/Raleway-ThinItalic.ttf
    - family: Noto_Sans_Kawi
      fonts:
        - asset: assets/font/Noto_Sans_Kawi/static/NotoSansKawi-Bold.ttf
        - asset: assets/font/Noto_Sans_Kawi/static/NotoSansKawi-Medium.ttf
        - asset: assets/font/Noto_Sans_Kawi/static/NotoSansKawi-Regular.ttf
        - asset: assets/font/Noto_Sans_Kawi/static/NotoSansKawi-SemiBold.ttf
